export const demoGalleryData = [
  // --- Places (8) ---
  {
    id: "masai_mara",
    title: "MASAI MARA",
    category: "Place",
    subtitle: "Tracking wild savannah horizons, African wildlife, and raw nature safaris.",
    left: "47.6%",
    top: "22.0%",
    width: "8.8%",
    height: "10.8%",
    artImg: "/images/aboutpage/gallery/frames/frame_5_masaimara_4x.png",
    photoImg: "/images/aboutpage/gallery/wildlife/vid1.mp4",
    galleryImages: [
      { type: "video", src: "/images/aboutpage/gallery/Wildlife/vid1.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/Wildlife/vid2.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/Wildlife/vid3.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/Wildlife/vid4.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/Wildlife/vid5.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/Wildlife/vid6.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/Wildlife/vid7.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/Wildlife/vid8.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/Wildlife/vid9.mp4" },
    ]
  },
  {
    id: "cairo",
    title: "CAIRO",
    category: "Place",
    subtitle: "Uncovering ancient Nile wonders, monumental pyramids, and rich Egyptian heritage.",
    left: "31.0%",
    top: "25.5%",
    width: "6.8%",
    height: "8.5%",
    artImg: "/images/aboutpage/gallery/frames/frame_3_cairo_4x.png",
    photoImg: "/images/aboutpage/gallery/egypt/img1.webp",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/egypt/img1.webp" },
      { type: "img", src: "/images/aboutpage/gallery/egypt/img2.webp" },
      { type: "img", src: "/images/aboutpage/gallery/egypt/img3.webp" },
      { type: "img", src: "/images/aboutpage/gallery/egypt/img4.webp" },
      { type: "img", src: "/images/aboutpage/gallery/egypt/img5.webp" },
      { type: "img", src: "/images/aboutpage/gallery/egypt/img6.webp" },
      { type: "video", src: "/images/aboutpage/gallery/egypt/vid1.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/egypt/vid2.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/egypt/vid3.mp4" },
    ]
  },
  {
    id: "stockholm",
    title: "STOCKHOLM",
    category: "Place",
    subtitle: "Exploring Nordic archipelagos, cobblestone alleys, and luminous Scandinavian sunsets.",
    left: "40.2%",
    top: "24.2%",
    width: "4.4%",
    height: "6.8%",
    artImg: "/images/aboutpage/gallery/frames/frame_2_stockholm_4x.png",
    photoImg: "/images/aboutpage/gallery/demo_media/stockholm_1.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/demo_media/stockholm_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/stockholm_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/stockholm_3.jpg" },
    ]
  },
  {
    id: "dubai",
    title: "DUBAI",
    category: "Place",
    subtitle: "Witnessing futuristic skyscrapers rise from golden desert dunes and horizons.",
    left: "59.2%",
    top: "23.2%",
    width: "5.2%",
    height: "10.5%",
    artImg: "/images/aboutpage/gallery/frames/frame_7_dubai_4x.png",
    photoImg: "/images/aboutpage/gallery/dubai/img1.webp",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/dubai/img1.webp" },
      { type: "img", src: "/images/aboutpage/gallery/dubai/img2.webp" },
      { type: "img", src: "/images/aboutpage/gallery/dubai/img3.webp" },
      { type: "img", src: "/images/aboutpage/gallery/dubai/img4.webp" },
      { type: "video", src: "/images/aboutpage/gallery/dubai/vid1.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/dubai/vid2.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/dubai/vid3.mp4" },
    ]
  },
  {
    id: "bali",
    title: "BALI",
    category: "Place",
    subtitle: "Finding tranquility amidst emerald rice terraces and ocean temple breezes.",
    left: "29.2%",
    top: "38.0%",
    width: "4.6%",
    height: "5.8%",
    artImg: "/images/aboutpage/gallery/frames/frame_6_bali_4x.png",
    photoImg: "/images/aboutpage/gallery/demo_media/bali_1.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/demo_media/bali_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/bali_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/bali_3.jpg" },
    ]
  },
  {
    id: "london",
    title: "LONDON",
    category: "Place",
    subtitle: "Walking historic Thames cobblestones surrounded by timeless architecture and culture.",
    left: "53.4%",
    top: "46.6%",
    width: "7.2%",
    height: "8.2%",
    artImg: "/images/aboutpage/gallery/frames/frame_15_london_4x.png",
    photoImg: "/images/aboutpage/gallery/london/vid1.mp4",
    galleryImages: [
      { type: "video", src: "/images/aboutpage/gallery/london/vid1.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/london/vid2.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/london/vid3.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/london/vid4.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/london/vid5.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/london/vid6.mp4" },
    ]
  },
  {
    id: "new_york",
    title: "NEW YORK",
    category: "Place",
    subtitle: "Feeling Manhattan grid energy, electric skylines, and relentless urban rhythm.",
    left: "47.6%",
    top: "34.2%",
    width: "5.2%",
    height: "10.5%",
    artImg: "/images/aboutpage/gallery/frames/frame_4_ny_4x.png",
    photoImg: "/images/aboutpage/gallery/ny.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/ny.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/ny_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/ny_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/ny_3.jpg" },
    ]
  },
  {
    id: "melbourne",
    title: "MELBOURNE",
    category: "Place",
    subtitle: "Wandering vibrant graffiti laneways and discovering world-class specialty coffee culture.",
    left: "54.0%",
    top: "34.2%",
    width: "5.4%",
    height: "10.5%",
    artImg: "/images/aboutpage/gallery/frames/frame_11_melbourne_4x.png",
    photoImg: "/images/aboutpage/gallery/demo_media/melbourne_1.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/demo_media/melbourne_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/melbourne_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/melbourne_3.jpg" },
    ]
  },

  // --- Doing (7) ---
  {
    id: "improv",
    title: "IMPROV",
    category: "Doing",
    subtitle: "Embracing unscripted stage presence, spontaneous trust, and creative theatrical comedy.",
    left: "34.6%",
    top: "37.5%",
    width: "4.0%",
    height: "7.0%",
    artImg: "/images/aboutpage/gallery/frames/frame_1_improv_4x.png",
    photoImg: "/images/aboutpage/gallery/demo_media/improv_1.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/demo_media/improv_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/improv_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/improv_3.jpg" },
    ]
  },
  {
    id: "philosophy",
    title: "PHILOSOPHY",
    category: "Doing",
    subtitle: "Engaging deep intellectual inquiry, existential texts, and contemplative philosophical clarity.",
    left: "39.4%",
    top: "32.2%",
    width: "7.2%",
    height: "12.8%",
    artImg: "/images/aboutpage/gallery/frames/frame_8_philosophy_4x.png",
    photoImg: "/images/aboutpage/gallery/demo_media/philosophy_1.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/demo_media/philosophy_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/philosophy_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/philosophy_3.jpg" },
    ]
  },
  {
    id: "sailing",
    title: "SAILING",
    category: "Doing",
    subtitle: "Harnessing open ocean winds and navigating expansive deep blue seas.",
    left: "61.2%",
    top: "35.0%",
    width: "8.8%",
    height: "10.5%",
    artImg: "/images/aboutpage/gallery/frames/frame_10_sailing_4x.png",
    photoImg: "/images/aboutpage/gallery/demo_media/sailing_1.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/demo_media/sailing_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/sailing_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/sailing_3.jpg" },
    ]
  },
  {
    id: "recovery",
    title: "RECOVERY",
    category: "Doing",
    subtitle: "Restoring body and mind through hot saunas and cold plunges.",
    left: "61.4%",
    top: "46.8%",
    width: "5.8%",
    height: "6.5%",
    artImg: "/images/aboutpage/gallery/frames/frame_9_recovery_4x.png",
    photoImg: "/images/aboutpage/gallery/demo_media/recovery_1.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/demo_media/recovery_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/recovery_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/recovery_3.jpg" },
    ]
  },
  {
    id: "mma",
    title: "MMA",
    category: "Doing",
    subtitle: "Building mental fortitude, martial arts discipline, and focused combat mastery.",
    left: "32.0%",
    top: "46.2%",
    width: "4.0%",
    height: "7.2%",
    artImg: "/images/aboutpage/gallery/frames/frame_12_mma_4x.png",
    photoImg: "/images/aboutpage/gallery/demo_media/mma_1.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/demo_media/mma_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/mma_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/mma_3.jpg" },
    ]
  },
  {
    id: "pottery",
    title: "POTTERY",
    category: "Doing",
    subtitle: "Shaping raw clay on the wheel into organic ceramic forms.",
    left: "36.8%",
    top: "46.8%",
    width: "5.6%",
    height: "6.0%",
    artImg: "/images/aboutpage/gallery/frames/frame_14_pottery_4x.png",
    photoImg: "/images/aboutpage/gallery/pottery/img1.webp",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/pottery/img1.webp" },
      { type: "img", src: "/images/aboutpage/gallery/pottery/img2.webp" },
      { type: "img", src: "/images/aboutpage/gallery/pottery/img3.webp" },
      { type: "img", src: "/images/aboutpage/gallery/pottery/img4.webp" },
      { type: "img", src: "/images/aboutpage/gallery/pottery/img5.webp" },
      { type: "video", src: "/images/aboutpage/gallery/pottery/vid2.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/pottery/vid3.mp4" },
    ]
  },
  {
    id: "diving",
    title: "DIVING",
    category: "Doing",
    subtitle: "Descending into tranquil ocean depths, coral reefs, and silent waters.",
    left: "43.0%",
    top: "46.2%",
    width: "5.0%",
    height: "9.6%",
    artImg: "/images/aboutpage/gallery/frames/frame_13_diving_4x.png",
    photoImg: "/images/aboutpage/gallery/demo_media/diving_1.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/demo_media/diving_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/diving_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/diving_3.jpg" },
    ]
  }
];
