export const demoGalleryData = [
  // --- Places (8) ---
  {
    id: "masai_mara",
    title: "MASAI MARA",
    category: "Place",
    subtitle: "Kenya Wildlife Safari",
    left: "47.275%",
    top: "30.599%",
    width: "5.451%",
    height: "12.109%",
    artImg: "/images/aboutpage/gallery/frames/frame_5_masaimara_4x.png",
    photoImg: "/images/aboutpage/gallery/wildlife/vid1.mp4",
    galleryImages: [
      { type: "video", src: "/images/aboutpage/gallery/Wildlife/vid1.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/Wildlife/vid2.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/Wildlife/vid3.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/Wildlife/vid4.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/Wildlife/vid5.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/Wildlife/vid6.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/Wildlife/vid7.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/Wildlife/vid8.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/Wildlife/vid9.mp4" },
    ]
  },
  {
    id: "stockholm",
    title: "STOCKHOLM",
    category: "Place",
    subtitle: "Nordic Archipelago & Light",
    left: "44.295%",
    top: "34.115%",
    width: "2.762%",
    height: "4.557%",
    artImg: "/images/aboutpage/gallery/frames/frame_2_stockholm_4x.png",
    photoImg: "/images/aboutpage/gallery/demo_media/stockholm_1.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/demo_media/stockholm_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/stockholm_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/stockholm_3.jpg" },
    ]
  },
  {
    id: "cairo",
    title: "CAIRO",
    category: "Place",
    subtitle: "Pyramids & Nile Heritage",
    left: "44.295%",
    top: "39.063%",
    width: "2.762%",
    height: "6.771%",
    artImg: "/images/aboutpage/gallery/frames/frame_3_cairo_4x.png",
    photoImg: "/images/aboutpage/gallery/egypt/img1.webp",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/egypt/img1.webp" },
      { type: "img", src: "/images/aboutpage/gallery/egypt/img2.webp" },
      { type: "img", src: "/images/aboutpage/gallery/egypt/img3.webp" },
      { type: "img", src: "/images/aboutpage/gallery/egypt/img4.webp" },
      { type: "img", src: "/images/aboutpage/gallery/egypt/img5.webp" },
      { type: "img", src: "/images/aboutpage/gallery/egypt/img6.webp" },
      { type: "video", src: "/images/aboutpage/gallery/egypt/vid1.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/egypt/vid2.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/egypt/vid3.mp4" },
    ]
  },
  {
    id: "new_york",
    title: "NEW YORK",
    category: "Place",
    subtitle: "Manhattan & Metropolis Rhythm",
    left: "44.295%",
    top: "46.224%",
    width: "2.762%",
    height: "7.031%",
    artImg: "/images/aboutpage/gallery/frames/frame_4_ny_4x.png",
    photoImg: "/images/aboutpage/gallery/ny.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/ny.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/ny_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/ny_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/ny_3.jpg" },
    ]
  },
  {
    id: "bali",
    title: "BALI",
    category: "Place",
    subtitle: "Tropical Terraces & Serenity",
    left: "47.275%",
    top: "43.229%",
    width: "2.762%",
    height: "4.688%",
    artImg: "/images/aboutpage/gallery/frames/frame_6_bali_4x.png",
    photoImg: "/images/aboutpage/gallery/demo_media/bali_1.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/demo_media/bali_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/bali_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/bali_3.jpg" },
    ]
  },
  {
    id: "dubai",
    title: "DUBAI",
    category: "Place",
    subtitle: "Desert Architecture & Future",
    left: "47.275%",
    top: "48.307%",
    width: "2.762%",
    height: "7.422%",
    artImg: "/images/aboutpage/gallery/frames/frame_7_dubai_4x.png",
    photoImg: "/images/aboutpage/gallery/dubai/img1.webp",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/dubai/img1.webp" },
      { type: "img", src: "/images/aboutpage/gallery/dubai/img2.webp" },
      { type: "img", src: "/images/aboutpage/gallery/dubai/img3.webp" },
      { type: "img", src: "/images/aboutpage/gallery/dubai/img4.webp" },
      { type: "video", src: "/images/aboutpage/gallery/dubai/vid1.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/dubai/vid2.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/dubai/vid3.mp4" },
    ]
  },
  {
    id: "melbourne",
    title: "MELBOURNE",
    category: "Place",
    subtitle: "Art Laneways & Coastline",
    left: "56.141%",
    top: "33.203%",
    width: "2.762%",
    height: "7.292%",
    artImg: "/images/aboutpage/gallery/frames/frame_11_melbourne_4x.png",
    photoImg: "/images/aboutpage/gallery/demo_media/melbourne_1.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/demo_media/melbourne_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/melbourne_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/melbourne_3.jpg" },
    ]
  },
  {
    id: "london",
    title: "LONDON",
    category: "Place",
    subtitle: "Thames, History & Atmosphere",
    left: "59.121%",
    top: "43.620%",
    width: "2.762%",
    height: "7.552%",
    artImg: "/images/aboutpage/gallery/frames/frame_15_london_4x.png",
    photoImg: "/images/aboutpage/gallery/london/vid1.mp4",
    galleryImages: [
      { type: "video", src: "/images/aboutpage/gallery/london/vid1.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/london/vid2.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/london/vid3.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/london/vid4.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/london/vid5.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/london/vid6.mp4" },
    ]
  },

  // --- Doing (7) ---
  {
    id: "improv",
    title: "IMPROV",
    category: "Doing",
    subtitle: "Spontaneity, Stage & Play",
    left: "41.315%",
    top: "41.797%",
    width: "2.762%",
    height: "7.292%",
    artImg: "/images/aboutpage/gallery/frames/frame_1_improv_4x.png",
    photoImg: "/images/aboutpage/gallery/demo_media/improv_1.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/demo_media/improv_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/improv_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/improv_3.jpg" },
    ]
  },
  {
    id: "philosophy",
    title: "PHILOSOPHY",
    category: "Doing",
    subtitle: "Inquiry, Books & Thought",
    left: "50.254%",
    top: "43.880%",
    width: "2.762%",
    height: "6.771%",
    artImg: "/images/aboutpage/gallery/frames/frame_8_philosophy_4x.png",
    photoImg: "/images/aboutpage/gallery/demo_media/philosophy_1.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/demo_media/philosophy_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/philosophy_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/philosophy_3.jpg" },
    ]
  },
  {
    id: "recovery",
    title: "RECOVERY",
    category: "Doing",
    subtitle: "Sauna, Cold Plunge & Zen",
    left: "53.161%",
    top: "31.510%",
    width: "2.762%",
    height: "7.422%",
    artImg: "/images/aboutpage/gallery/frames/frame_9_recovery_4x.png",
    photoImg: "/images/aboutpage/gallery/demo_media/recovery_1.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/demo_media/recovery_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/recovery_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/recovery_3.jpg" },
    ]
  },
  {
    id: "sailing",
    title: "SAILING",
    category: "Doing",
    subtitle: "Open Ocean Wind & Rigging",
    left: "53.161%",
    top: "39.453%",
    width: "2.762%",
    height: "7.552%",
    artImg: "/images/aboutpage/gallery/frames/frame_10_sailing_4x.png",
    photoImg: "/images/aboutpage/gallery/demo_media/sailing_1.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/demo_media/sailing_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/sailing_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/sailing_3.jpg" },
    ]
  },
  {
    id: "mma",
    title: "MMA",
    category: "Doing",
    subtitle: "Discipline, Sparring & Power",
    left: "56.141%",
    top: "41.016%",
    width: "2.762%",
    height: "7.552%",
    artImg: "/images/aboutpage/gallery/frames/frame_12_mma_4x.png",
    photoImg: "/images/aboutpage/gallery/demo_media/mma_1.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/demo_media/mma_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/mma_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/mma_3.jpg" },
    ]
  },
  {
    id: "diving",
    title: "DIVING",
    category: "Doing",
    subtitle: "Deep Blue Reefs & Silence",
    left: "56.141%",
    top: "48.958%",
    width: "2.762%",
    height: "7.682%",
    artImg: "/images/aboutpage/gallery/frames/frame_13_diving_4x.png",
    photoImg: "/images/aboutpage/gallery/demo_media/diving_1.jpg",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/demo_media/diving_1.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/diving_2.jpg" },
      { type: "img", src: "/images/aboutpage/gallery/demo_media/diving_3.jpg" },
    ]
  },
  {
    id: "pottery",
    title: "POTTERY",
    category: "Doing",
    subtitle: "Clay, Form & Wheel Texture",
    left: "59.121%",
    top: "35.547%",
    width: "2.762%",
    height: "7.552%",
    artImg: "/images/aboutpage/gallery/frames/frame_14_pottery_4x.png",
    photoImg: "/images/aboutpage/gallery/pottery/img1.webp",
    galleryImages: [
      { type: "img", src: "/images/aboutpage/gallery/pottery/img1.webp" },
      { type: "img", src: "/images/aboutpage/gallery/pottery/img2.webp" },
      { type: "img", src: "/images/aboutpage/gallery/pottery/img3.webp" },
      { type: "img", src: "/images/aboutpage/gallery/pottery/img4.webp" },
      { type: "img", src: "/images/aboutpage/gallery/pottery/img5.webp" },
      { type: "video", src: "/images/aboutpage/gallery/pottery/vid2.mp4" },
      { type: "video", src: "/images/aboutpage/gallery/pottery/vid3.mp4" },
    ]
  }
];
